tinyMCE.addI18n('en.wpvitrinefrugar', {
	longname: 'WP Vitrine Frugar'
	, embed_desc: 'Embed content'
	, video: 'Video'
	, image: 'Image'
	, link : 'Link'
	, rich : 'Rich content'
	, url_title: 'URL'
	, url_hint: 'Please enter video url'
	, width_title: 'Max Width'
	, height_title: 'Max Height'
	, preview_title: 'Preview'
	, preview_button: 'click to preview'
	, submit: 'Embed'
	, hidepreview_button: 'hide preview'
	, has_additional_fields: 'Show additional fields'
}); 